server:
 port: 8009
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/phase2
  username: root
  password: 2002
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  hibernate.ddl-auto: update
  show-sql: true
